### ISSUE TITLE
Main page

### ISSUE THREAD

**Issue by DrD1esel** [DrD1esel/IvanPractice#1]
As a user I want to see on the main page:

- Header with logo and application name (feel free to choose whatever you want)
- List of three latest posts form the server (`createdAt` field of post entity). Posts should be rendered in separate components, the info to display: `title`, `body`, `createdAt` date in human readable format.

Here and further provide screenshots of implemented functionality

Useful links:
- [Json-server docs](https://www.npmjs.com/package/json-server/v/0.17.4)
- [Library for work with dates](https://day.js.org/docs/en/installation/typescript)

**Comment by Nekovector** [comment]
![Снимок экрана (856)](https://github.com/DrD1esel/IvanPractice/assets/136462495/a1dfed80-246b-4d0e-8fcb-d86cd4b6d9c2)
